// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadDockerFile(arg1, arg2, arg3) {
  return window['go']['services']['FileService']['DownloadDockerFile'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['services']['FileService']['Startup'](arg1);
}
